In [51]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

#using this proximity measure
#vectors as parameters to compute euclidean distnce
def euclid(vec1, vec2):
    euclidean_dist = np.sqrt(sum((vec1-vec2)**2))
    return euclidean_dist

#fucntion to sort what you want to sort by
#second column
def sortKey(item):
    return item[1]

def knearest(vec, data, k):
    #to store distance of each row for sorting
    #empty array
    result = []
    #compute distance between given vec and each other row in the data table
    for row in range (0, len(data)):
        distance = euclid(vec, data[row])
        #store the distance to sort later 
        #store the row and the distance number
        result.append([row, distance])
    #test
    #for i in range(len(data)):
       #print(data[i])
    #sort the results based on distance (2 column)
    #sorted is a function within python pass the array and what you want to sort
    #which is the second column
    sortedResult = sorted(result, key=sortKey)
    
    print('\033[1m' + "Sorted results" + '\033[0m')
    for i in range(len(sortedResult)):
        print(sortedResult[i])
        
    indicies = []
    
    if k<len(data):
        for r in range(0, k):
            indicies.append(sortedResult[r][0])
    else:
        indicies = [i[0] for i in sortedResult]
        
    return indicies
        

data = np.array([[10,3,3,5,10],
                [5,4,5,3,6],
                [10,4,6,4,9],
                [8,6,2,6,3],
                [10,3,3,5,8],
                [9,2,1,2,11],
                [9,3,1,2,11]])




#find k nearest neighbors of reference vector
givenVec = data[1];
for i in range(len(data)):
    print(data[i])
knn = knearest(givenVec, data, 7)
#print('\033[1m' + "3 nearest neighbors of row 0" + '\033[0m')
print("knn: ", knn)

#### another way #####
print()
nbrs = NearestNeighbors(n_neighbors=7, algorithm='ball_tree').fit(data)
distances, indices = nbrs.kneighbors(data)

print(distances)
print(indices)

[10  3  3  5 10]
[5 4 5 3 6]
[10  4  6  4  9]
[8 6 2 6 3]
[10  3  3  5  8]
[ 9  2  1  2 11]
[ 9  3  1  2 11]
Sorted results
[1, 0.0]
[2, 6.0]
[4, 6.164414002968976]
[3, 6.324555320336759]
[0, 7.0710678118654755]
[6, 7.681145747868608]
[5, 7.874007874011811]
knn:  [1, 2, 4, 3, 0, 6, 5]

[[0.         2.         3.46410162 3.87298335 4.         7.07106781
  8.        ]
 [0.         6.         6.164414   6.32455532 7.07106781 7.68114575
  7.87400787]
 [0.         3.46410162 3.46410162 5.91607978 6.         6.164414
  8.        ]
 [0.         6.32455532 6.32455532 8.         8.         9.53939201
  9.89949494]
 [0.         2.         3.46410162 4.79583152 4.89897949 6.164414
  6.32455532]
 [0.         1.         4.         4.89897949 6.164414   7.87400787
  9.89949494]
 [0.         1.         3.87298335 4.79583152 5.91607978 7.68114575
  9.53939201]]
[[0 4 2 6 5 1 3]
 [1 2 4 3 0 6 5]
 [2 0 4 6 1 5 3]
 [3 4 1 0 2 6 5]
 [4 0 2 6 5 1 3]
 [5 6 0 4 2 1 3]
 [6 5 0 4 2 1 3]]
